# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/endeavoru/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/endeavoru/proprietary/bin/akmd:/system/bin/akmd \
    vendor/htc/endeavoru/proprietary/bin/charging:/system/bin/charging \
    vendor/htc/endeavoru/proprietary/bin/cplc_main:/system/bin/cplc_main \
    vendor/htc/endeavoru/proprietary/bin/ewtzmud:/system/bin/ewtzmud \
    vendor/htc/endeavoru/proprietary/bin/htcbatt:/system/bin/htcbatt \
    vendor/htc/endeavoru/proprietary/bin/InjectionTool:/system/bin/InjectionTool \
    vendor/htc/endeavoru/proprietary/bin/gsm0710muxd:/system/bin/gsm0710muxd \
    vendor/htc/endeavoru/proprietary/bin/GPSCConfigFile.cfg:/system/bin/GPSCConfigFile.cfg \
    vendor/htc/endeavoru/proprietary/bin/GpsConfigFile.txt:/system/bin/GpsConfigFile.txt \
    vendor/htc/endeavoru/proprietary/bin/hdmid:/system/bin/hdmid \
    vendor/htc/endeavoru/proprietary/bin/IMCdownload:/system/bin/IMCdownload \
    vendor/htc/endeavoru/proprietary/bin/make_sec_bin:/system/bin/make_sec_bin \
    vendor/htc/endeavoru/proprietary/bin/mknod:/system/bin/mknod \
    vendor/htc/endeavoru/proprietary/bin/navl_server:/system/bin/navl_server \
    vendor/htc/endeavoru/proprietary/bin/nvm_server:/system/bin/nvm_server \
    vendor/htc/endeavoru/proprietary/bin/uim-sysfs:/system/bin/uim-sysfs \
    vendor/htc/endeavoru/proprietary/bin/patch-X.0.ce:/system/bin/patch-X.0.ce \
    vendor/htc/endeavoru/proprietary/bin/poweron_modem_fls.sh:/system/bin/poweron_modem_fls.sh \
    vendor/htc/endeavoru/proprietary/bin/rild:/system/bin/rild \
    vendor/htc/endeavoru/proprietary/bin/RXN_IntApp:/system/bin/RXN_IntApp

PRODUCT_COPY_FILES += \
    vendor/htc/endeavoru/proprietary/lib/egl/libEGL_perfhud.so:/system/lib/egl/libEGL_perfhud.so \
    vendor/htc/endeavoru/proprietary/lib/egl/libEGL_tegra.so:/system/lib/egl/libEGL_tegra.so \
    vendor/htc/endeavoru/proprietary/lib/egl/libGLESv1_CM_perfhud.so:/system/lib/egl/libGLESv1_CM_perfhud.so \
    vendor/htc/endeavoru/proprietary/lib/egl/libGLESv1_CM_tegra.so:/system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/htc/endeavoru/proprietary/lib/egl/libGLESv2_perfhud.so:/system/lib/egl/libGLESv2_perfhud.so \
    vendor/htc/endeavoru/proprietary/lib/egl/libGLESv2_tegra.so:/system/lib/egl/libGLESv2_tegra.so \
    vendor/htc/endeavoru/proprietary/lib/hw/audio.primary.tegra.so:/system/lib/hw/audio.primary.tegra.so \
    vendor/htc/endeavoru/proprietary/lib/hw/audio_policy.tegra.so:/system/lib/hw/audio_policy.tegra.so \
    vendor/htc/endeavoru/proprietary/lib/hw/camera.tegra.so:/system/lib/hw/camera.tegra.so \
    vendor/htc/endeavoru/proprietary/lib/hw/gps.tegra.so:/system/lib/hw/gps.tegra.so \
    vendor/htc/endeavoru/proprietary/lib/hw/gralloc.tegra.so:/system/lib/hw/gralloc.tegra.so \
    vendor/htc/endeavoru/proprietary/lib/hw/hwcomposer.tegra.so:/system/lib/hw/hwcomposer.tegra.so \
    vendor/htc/endeavoru/proprietary/lib/hw/nfc.endeavoru.so:/system/lib/hw/nfc.endeavoru.so \
    vendor/htc/endeavoru/proprietary/lib/hw/sensors.endeavoru.so:/system/lib/hw/sensors.endeavoru.so \
    vendor/htc/endeavoru/proprietary/lib/libardrv_dynamic.so:/system/lib/libardrv_dynamic.so \
    vendor/htc/endeavoru/proprietary/lib/libasound.so:/system/lib/libasound.so \
    vendor/htc/endeavoru/proprietary/lib/libaudioflinger.so:/system/lib/libaudioflinger.so \
    vendor/htc/endeavoru/proprietary/lib/libcgdrv.so:/system/lib/libcgdrv.so \
    vendor/htc/endeavoru/proprietary/lib/libcall_volume.so:/system/lib/libcall_volume.so \
    vendor/htc/endeavoru/proprietary/lib/libdumppcm.so:/system/lib/libdumppcm.so \
    vendor/htc/endeavoru/proprietary/lib/libhtc_dis.so:/system/lib/libhtc_dis.so \
    vendor/htc/endeavoru/proprietary/lib/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/endeavoru/proprietary/lib/libhtcsurfaces.so:/system/lib/libhtcsurfaces.so \
    vendor/htc/endeavoru/proprietary/lib/libgpsservices.so:/system/lib/libgpsservices.so \
    vendor/htc/endeavoru/proprietary/lib/libgps.so:/system/lib/libgps.so \
    vendor/htc/endeavoru/proprietary/lib/libmcphalgps.so:/system/lib/libmcphalgps.so \
    vendor/htc/endeavoru/proprietary/lib/libmedia.so:/system/lib/libmedia.so \
    vendor/htc/endeavoru/proprietary/lib/libmllite.so:/system/lib/libmllite.so \
    vendor/htc/endeavoru/proprietary/lib/libmlplatform.so:/system/lib/libmlplatform.so \
    vendor/htc/endeavoru/proprietary/lib/libmpl.so:/system/lib/libmpl.so \
    vendor/htc/endeavoru/proprietary/lib/libmpl_jni.so:/system/lib/libmpl_jni.so \
    vendor/htc/endeavoru/proprietary/lib/libnvapputil.so:/system/lib/libnvapputil.so \
    vendor/htc/endeavoru/proprietary/lib/libnvasfparserhal.so:/system/lib/libnvasfparserhal.so \
    vendor/htc/endeavoru/proprietary/lib/libnvaviparserhal.so:/system/lib/libnvaviparserhal.so \
    vendor/htc/endeavoru/proprietary/lib/libnvavp.so:/system/lib/libnvavp.so \
    vendor/htc/endeavoru/proprietary/lib/libnvcontrol_jni.so:/system/lib/libnvcontrol_jni.so \
    vendor/htc/endeavoru/proprietary/lib/libnvcpud_client.so:/system/lib/libnvcpud_client.so \
    vendor/htc/endeavoru/proprietary/lib/libnvcpud.so:/system/lib/libnvcpud.so \
    vendor/htc/endeavoru/proprietary/lib/libnvddk_2d.so:/system/lib/libnvddk_2d.so \
    vendor/htc/endeavoru/proprietary/lib/libnvddk_2d_v2.so:/system/lib/libnvddk_2d_v2.so \
    vendor/htc/endeavoru/proprietary/lib/libnvdispmgr_d.so:/system/lib/libnvdispmgr_d.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_asfparser.so:/system/lib/libnvmm_asfparser.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_audio.so:/system/lib/libnvmm_audio.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_aviparser.so:/system/lib/libnvmm_aviparser.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_camera.so:/system/lib/libnvmm_camera.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_contentpipe.so:/system/lib/libnvmm_contentpipe.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_image.so:/system/lib/libnvmm_image.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmmlite.so:/system/lib/libnvmmlite.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmmlite_audio.so:/system/lib/libnvmmlite_audio.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmmlite_image.so:/system/lib/libnvmmlite_image.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmmlite_msaudio.so:/system/lib/libnvmmlite_msaudio.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmmlite_utils.so:/system/lib/libnvmmlite_utils.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmmlite_video.so:/system/lib/libnvmmlite_video.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_manager.so:/system/lib/libnvmm_manager.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_misc.so:/system/lib/libnvmm_misc.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_msaudio.so:/system/lib/libnvmm_msaudio.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_parser.so:/system/lib/libnvmm_parser.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_service.so:/system/lib/libnvmm_service.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm.so:/system/lib/libnvmm.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_utils.so:/system/lib/libnvmm_utils.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_vc1_video.so:/system/lib/libnvmm_vc1_video.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_video.so:/system/lib/libnvmm_video.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_vp6_video.so:/system/lib/libnvmm_vp6_video.so \
    vendor/htc/endeavoru/proprietary/lib/libnvmm_writer.so:/system/lib/libnvmm_writer.so \
    vendor/htc/endeavoru/proprietary/lib/libnvodm_dtvtuner.so:/system/lib/libnvodm_dtvtuner.so \
    vendor/htc/endeavoru/proprietary/lib/libnvodm_hdmi.so:/system/lib/libnvodm_hdmi.so \
    vendor/htc/endeavoru/proprietary/lib/libnvodm_imager.so:/system/lib/libnvodm_imager.so \
    vendor/htc/endeavoru/proprietary/lib/libnvodm_misc.so:/system/lib/libnvodm_misc.so \
    vendor/htc/endeavoru/proprietary/lib/libnvodm_query.so:/system/lib/libnvodm_query.so \
    vendor/htc/endeavoru/proprietary/lib/libnvomxilclient.so:/system/lib/libnvomxilclient.so \
    vendor/htc/endeavoru/proprietary/lib/libnvomx.so:/system/lib/libnvomx.so \
    vendor/htc/endeavoru/proprietary/lib/libnvos.so:/system/lib/libnvos.so \
    vendor/htc/endeavoru/proprietary/lib/libnvparser.so:/system/lib/libnvparser.so \
    vendor/htc/endeavoru/proprietary/lib/libnvrm_graphics.so:/system/lib/libnvrm_graphics.so \
    vendor/htc/endeavoru/proprietary/lib/libnvrm.so:/system/lib/libnvrm.so \
    vendor/htc/endeavoru/proprietary/lib/libnvsm.so:/system/lib/libnvsm.so \
    vendor/htc/endeavoru/proprietary/lib/libnvtvmr.so:/system/lib/libnvtvmr.so \
    vendor/htc/endeavoru/proprietary/lib/libnvwinsys.so:/system/lib/libnvwinsys.so \
    vendor/htc/endeavoru/proprietary/lib/libnvwsi.so:/system/lib/libnvwsi.so \
    vendor/htc/endeavoru/proprietary/lib/libOlaBase.so:/system/lib/libOlaBase.so \
    vendor/htc/endeavoru/proprietary/lib/libOlaEngine.so:/system/lib/libOlaEngine.so \
    vendor/htc/endeavoru/proprietary/lib/libolaworks.so:/system/lib/libolaworks.so \
    vendor/htc/endeavoru/proprietary/lib/libposteffect.so:/system/lib/libposteffect.so \
    vendor/htc/endeavoru/proprietary/lib/libril.so:/system/lib/libril.so \
    vendor/htc/endeavoru/proprietary/lib/libscalado.so:/system/lib/libscalado.so \
    vendor/htc/endeavoru/proprietary/lib/libsensors_mpl.so:/system/lib/libsensors_mpl.so \
    vendor/htc/endeavoru/proprietary/lib/libsrscorehtc.so:/system/lib/libsrscorehtc.so \
    vendor/htc/endeavoru/proprietary/lib/libsrsprocessing.so:/system/lib/libsrsprocessing.so \
    vendor/htc/endeavoru/proprietary/lib/libstagefrighthw.so:/system/lib/libstagefrighthw.so \
    vendor/htc/endeavoru/proprietary/lib/libsupllocationprovider.so:/system/lib/libsupllocationprovider.so \
    vendor/htc/endeavoru/proprietary/lib/libwebkitaccel.so:/system/lib/libwebkitaccel.so

PRODUCT_COPY_FILES += \
    vendor/htc/endeavoru/proprietary/usr/keylayout/qwerty.kl:/system/usr/keylayout/qwerty.kl

PRODUCT_COPY_FILES += \
    vendor/htc/endeavoru/proprietary/media/audio/notifications/MessageAlert.ogg:/system/media/audio/notifications/MessageAlert.ogg

PRODUCT_COPY_FILES += \
    vendor/htc/endeavoru/proprietary/vendor/firmware/libpn544_fw.so:/system/vendor/firmware/libpn544_fw.so
